//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parakeet.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Parakeet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string ChangeFileNameView_AddRules {
            get {
                return ResourceManager.GetString("ChangeFileNameView_AddRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string ChangeFileNameView_DeleteRules {
            get {
                return ResourceManager.GetString("ChangeFileNameView_DeleteRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string ChangeFileNameView_HeaderActivated {
            get {
                return ResourceManager.GetString("ChangeFileNameView_HeaderActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string ChangeFileNameView_HeaderFirst {
            get {
                return ResourceManager.GetString("ChangeFileNameView_HeaderFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string ChangeFileNameView_HeaderSecond {
            get {
                return ResourceManager.GetString("ChangeFileNameView_HeaderSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string ChangeFileNameView_HeaderTarget {
            get {
                return ResourceManager.GetString("ChangeFileNameView_HeaderTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string Data_TaskCompleted_ActionExecuteOn {
            get {
                return ResourceManager.GetString("Data_TaskCompleted_ActionExecuteOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string Data_TaskCompleted_ActionUserCancel {
            get {
                return ResourceManager.GetString("Data_TaskCompleted_ActionUserCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string Data_TaskCompleted_Result {
            get {
                return ResourceManager.GetString("Data_TaskCompleted_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string Data_WriteData_Error {
            get {
                return ResourceManager.GetString("Data_WriteData_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string DirectoryControlView_AddDirectory {
            get {
                return ResourceManager.GetString("DirectoryControlView_AddDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string DirectoryControlView_DeleteEntry {
            get {
                return ResourceManager.GetString("DirectoryControlView_DeleteEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string DirectoryControlView_HeaderActivated {
            get {
                return ResourceManager.GetString("DirectoryControlView_HeaderActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string DirectoryControlView_HeaderFolder {
            get {
                return ResourceManager.GetString("DirectoryControlView_HeaderFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string DirectoryControlView_StartTask {
            get {
                return ResourceManager.GetString("DirectoryControlView_StartTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string DirectoryControlViewModel_DoAddDirectory_Select_a_folder_to_add____ {
            get {
                return ResourceManager.GetString("DirectoryControlViewModel_DoAddDirectory_Select_a_folder_to_add____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string DocDistView_Description {
            get {
                return ResourceManager.GetString("DocDistView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string DocDistView_Threshold {
            get {
                return ResourceManager.GetString("DocDistView_Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string ListContextMenuView_Delete {
            get {
                return ResourceManager.GetString("ListContextMenuView_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string ListContextMenuView_Down {
            get {
                return ResourceManager.GetString("ListContextMenuView_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string ListContextMenuView_Up {
            get {
                return ResourceManager.GetString("ListContextMenuView_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string MainWindow_ChangeName {
            get {
                return ResourceManager.GetString("MainWindow_ChangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string MainWindow_FindSimilitude {
            get {
                return ResourceManager.GetString("MainWindow_FindSimilitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string MainWindow_MainWindow_Error_File_Reading {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_Error_File_Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string MainWindow_RemoveFile {
            get {
                return ResourceManager.GetString("MainWindow_RemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string MainWindow_SortBy {
            get {
                return ResourceManager.GetString("MainWindow_SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string MenuView_Exit {
            get {
                return ResourceManager.GetString("MenuView_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string MenuView_FileHeader {
            get {
                return ResourceManager.GetString("MenuView_FileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string MenuView_Language {
            get {
                return ResourceManager.GetString("MenuView_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string MenuView_NewFile {
            get {
                return ResourceManager.GetString("MenuView_NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string MenuView_OpenFile {
            get {
                return ResourceManager.GetString("MenuView_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string MenuView_Save {
            get {
                return ResourceManager.GetString("MenuView_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string MenuView_SaveUnder {
            get {
                return ResourceManager.GetString("MenuView_SaveUnder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string MenuViewModel_DoNewFiles_Select_file_name___ {
            get {
                return ResourceManager.GetString("MenuViewModel_DoNewFiles_Select_file_name___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string MenuViewModel_DoOpenFiles_Select_a_xml_file {
            get {
                return ResourceManager.GetString("MenuViewModel_DoOpenFiles_Select_a_xml_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string MenuViewModel_DoOpenFiles_Xml_files____xml____xml {
            get {
                return ResourceManager.GetString("MenuViewModel_DoOpenFiles_Xml_files____xml____xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string MenuViewModel_DoSaveFilesUnder_Sous____ {
            get {
                return ResourceManager.GetString("MenuViewModel_DoSaveFilesUnder_Sous____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string MenuViewModel_DoSaveFilesUnder_Xml_files___xml______xml {
            get {
                return ResourceManager.GetString("MenuViewModel_DoSaveFilesUnder_Xml_files___xml______xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string RemoveFilesView_Add {
            get {
                return ResourceManager.GetString("RemoveFilesView_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string RemoveFilesView_Delete {
            get {
                return ResourceManager.GetString("RemoveFilesView_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string RemoveFilesView_HeaderActivated {
            get {
                return ResourceManager.GetString("RemoveFilesView_HeaderActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string RemoveFilesView_HeaderExtension {
            get {
                return ResourceManager.GetString("RemoveFilesView_HeaderExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string RemoveFilesView_HeaderString {
            get {
                return ResourceManager.GetString("RemoveFilesView_HeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string SortByView_AddRegex {
            get {
                return ResourceManager.GetString("SortByView_AddRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string SortByView_DeleteEntry {
            get {
                return ResourceManager.GetString("SortByView_DeleteEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string SortByView_HeaderActivated {
            get {
                return ResourceManager.GetString("SortByView_HeaderActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string SortByView_HeaderRegex {
            get {
                return ResourceManager.GetString("SortByView_HeaderRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string StatusBarView_Cancel {
            get {
                return ResourceManager.GetString("StatusBarView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string StatusBarView_File {
            get {
                return ResourceManager.GetString("StatusBarView_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string StatusBarViewModel_StatusTask_Running {
            get {
                return ResourceManager.GetString("StatusBarViewModel_StatusTask_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string StatusBarViewModel_StatusTask_Waiting {
            get {
                return ResourceManager.GetString("StatusBarViewModel_StatusTask_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string TaskView_Cancel {
            get {
                return ResourceManager.GetString("TaskView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string TaskView_DeleteDescrition {
            get {
                return ResourceManager.GetString("TaskView_DeleteDescrition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string TaskView_Recursive {
            get {
                return ResourceManager.GetString("TaskView_Recursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string TaskView_RenamingDescription {
            get {
                return ResourceManager.GetString("TaskView_RenamingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string TaskView_SortDescription {
            get {
                return ResourceManager.GetString("TaskView_SortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string TaskView_Start {
            get {
                return ResourceManager.GetString("TaskView_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string TaskView_TitleWindow {
            get {
                return ResourceManager.GetString("TaskView_TitleWindow", resourceCulture);
            }
        }
    }
}
