//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parakeet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Parakeet.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AppReadingError {
            get {
                return ResourceManager.GetString("AppReadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChangeFileNameView_AddRules {
            get {
                return ResourceManager.GetString("ChangeFileNameView_AddRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChangeFileNameView_DeleteRules {
            get {
                return ResourceManager.GetString("ChangeFileNameView_DeleteRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChangeFileNameView_HeaderActivated {
            get {
                return ResourceManager.GetString("ChangeFileNameView_HeaderActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChangeFileNameView_HeaderFirst {
            get {
                return ResourceManager.GetString("ChangeFileNameView_HeaderFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChangeFileNameView_HeaderSecond {
            get {
                return ResourceManager.GetString("ChangeFileNameView_HeaderSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChangeFileNameView_HeaderTarget {
            get {
                return ResourceManager.GetString("ChangeFileNameView_HeaderTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Data_TaskCompleted_ActionExecuteOn {
            get {
                return ResourceManager.GetString("Data_TaskCompleted_ActionExecuteOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Data_TaskCompleted_ActionUserCancel {
            get {
                return ResourceManager.GetString("Data_TaskCompleted_ActionUserCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Data_TaskCompleted_Result {
            get {
                return ResourceManager.GetString("Data_TaskCompleted_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Data_WriteData_Error {
            get {
                return ResourceManager.GetString("Data_WriteData_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DirectoryControlView_AddDirectory {
            get {
                return ResourceManager.GetString("DirectoryControlView_AddDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DirectoryControlView_DeleteEntry {
            get {
                return ResourceManager.GetString("DirectoryControlView_DeleteEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DirectoryControlView_HeaderActivated {
            get {
                return ResourceManager.GetString("DirectoryControlView_HeaderActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DirectoryControlView_HeaderFolder {
            get {
                return ResourceManager.GetString("DirectoryControlView_HeaderFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DirectoryControlView_StartTask {
            get {
                return ResourceManager.GetString("DirectoryControlView_StartTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DirectoryControlViewModel_DoAddDirectory_Select_a_folder_to_add____ {
            get {
                return ResourceManager.GetString("DirectoryControlViewModel_DoAddDirectory_Select_a_folder_to_add____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DocDistView_Description {
            get {
                return ResourceManager.GetString("DocDistView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DocDistView_Threshold {
            get {
                return ResourceManager.GetString("DocDistView_Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ListContextMenuView_Delete {
            get {
                return ResourceManager.GetString("ListContextMenuView_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ListContextMenuView_Down {
            get {
                return ResourceManager.GetString("ListContextMenuView_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ListContextMenuView_Up {
            get {
                return ResourceManager.GetString("ListContextMenuView_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_ChangeName {
            get {
                return ResourceManager.GetString("MainWindow_ChangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_FindSimilitude {
            get {
                return ResourceManager.GetString("MainWindow_FindSimilitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_MainWindow_Error_File_Reading {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_Error_File_Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_RemoveFile {
            get {
                return ResourceManager.GetString("MainWindow_RemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_SortBy {
            get {
                return ResourceManager.GetString("MainWindow_SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MenuView_Exit {
            get {
                return ResourceManager.GetString("MenuView_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MenuView_FileHeader {
            get {
                return ResourceManager.GetString("MenuView_FileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MenuView_Language {
            get {
                return ResourceManager.GetString("MenuView_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MenuView_NewFile {
            get {
                return ResourceManager.GetString("MenuView_NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MenuView_OpenFile {
            get {
                return ResourceManager.GetString("MenuView_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MenuView_Save {
            get {
                return ResourceManager.GetString("MenuView_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MenuView_SaveUnder {
            get {
                return ResourceManager.GetString("MenuView_SaveUnder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MenuViewModel_DoNewFiles_Select_file_name___ {
            get {
                return ResourceManager.GetString("MenuViewModel_DoNewFiles_Select_file_name___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MenuViewModel_DoOpenFiles_Select_a_xml_file {
            get {
                return ResourceManager.GetString("MenuViewModel_DoOpenFiles_Select_a_xml_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MenuViewModel_DoOpenFiles_Xml_files____xml____xml {
            get {
                return ResourceManager.GetString("MenuViewModel_DoOpenFiles_Xml_files____xml____xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MenuViewModel_DoSaveFilesUnder_Sous____ {
            get {
                return ResourceManager.GetString("MenuViewModel_DoSaveFilesUnder_Sous____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MenuViewModel_DoSaveFilesUnder_Xml_files___xml______xml {
            get {
                return ResourceManager.GetString("MenuViewModel_DoSaveFilesUnder_Xml_files___xml______xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RemoveFilesView_Add {
            get {
                return ResourceManager.GetString("RemoveFilesView_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RemoveFilesView_Delete {
            get {
                return ResourceManager.GetString("RemoveFilesView_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RemoveFilesView_HeaderActivated {
            get {
                return ResourceManager.GetString("RemoveFilesView_HeaderActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RemoveFilesView_HeaderExtension {
            get {
                return ResourceManager.GetString("RemoveFilesView_HeaderExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RemoveFilesView_HeaderString {
            get {
                return ResourceManager.GetString("RemoveFilesView_HeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ResultsView_DocDistCommand {
            get {
                return ResourceManager.GetString("ResultsView_DocDistCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ResultsView_Ok {
            get {
                return ResourceManager.GetString("ResultsView_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ResultsView_RemoveCommand {
            get {
                return ResourceManager.GetString("ResultsView_RemoveCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ResultsView_RenameCommand {
            get {
                return ResourceManager.GetString("ResultsView_RenameCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ResultsView_SortCommand {
            get {
                return ResourceManager.GetString("ResultsView_SortCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ResultsView_Title {
            get {
                return ResourceManager.GetString("ResultsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ResutlsView_DataCommand {
            get {
                return ResourceManager.GetString("ResutlsView_DataCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SortByView_AddRegex {
            get {
                return ResourceManager.GetString("SortByView_AddRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SortByView_DeleteEntry {
            get {
                return ResourceManager.GetString("SortByView_DeleteEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SortByView_HeaderActivated {
            get {
                return ResourceManager.GetString("SortByView_HeaderActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SortByView_HeaderRegex {
            get {
                return ResourceManager.GetString("SortByView_HeaderRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StatusBarView_Cancel {
            get {
                return ResourceManager.GetString("StatusBarView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StatusBarView_File {
            get {
                return ResourceManager.GetString("StatusBarView_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StatusBarViewModel_StatusTask_Running {
            get {
                return ResourceManager.GetString("StatusBarViewModel_StatusTask_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StatusBarViewModel_StatusTask_Waiting {
            get {
                return ResourceManager.GetString("StatusBarViewModel_StatusTask_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TaskView_Cancel {
            get {
                return ResourceManager.GetString("TaskView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TaskView_Checking {
            get {
                return ResourceManager.GetString("TaskView_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TaskView_DeleteDescrition {
            get {
                return ResourceManager.GetString("TaskView_DeleteDescrition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TaskView_Recursive {
            get {
                return ResourceManager.GetString("TaskView_Recursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TaskView_RenamingDescription {
            get {
                return ResourceManager.GetString("TaskView_RenamingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TaskView_SortDescription {
            get {
                return ResourceManager.GetString("TaskView_SortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TaskView_Start {
            get {
                return ResourceManager.GetString("TaskView_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TaskView_TitleWindow {
            get {
                return ResourceManager.GetString("TaskView_TitleWindow", resourceCulture);
            }
        }
    }
}
